name: Auto Deploy to Server via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via LFTP
        run: |
          lftp -c "
          set ftp:ssl-allow no;
          open -u '${{ secrets.FTP_USERNAME }}','${{ secrets.FTP_PASSWORD }}' '${{ secrets.FTP_SERVER }}';
          mirror --reverse --delete --verbose --exclude-glob .git* --exclude-glob .git*/** ./ /;
          quit;
          "
